name: ARM64
on: [pull_request]

env:
  BUILD_TYPE: Release
  ASAN: OFF
  ARCH: LLVM
  C_COMPILER: /usr/bin/clang
  CXX_COMPILER: /usr/bin/clang++

jobs:
  build:
    name: Build and Test
    runs-on: [self-hosted, ARM64]
    container:
      image: ubuntu:22.04
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        stack_walker: [LLVM_SHADOW_STACK, LLVM_STATEPOINT_EXAMPLE]
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        apt update
        apt -y install llvm clang libboost-all-dev libgtest-dev cmake clang-tidy

    - name: Build GTest
      run: |
        cd /usr/src/gtest
        cmake CMakeLists.txt
        make
        cp lib/*.a /usr/lib

    - name: Configure CMake
      run: | 
        cmake -B build --no-warn-unused-cli \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DASAN=${{env.ASAN}} \
        -DGCTYPE:STRING=${{matrix.stack_walker}} \
        -DARCH:STRING=${{env.ARCH}} \
        -DCMAKE_C_COMPILER:FILEPATH=${{env.C_COMPILER}} \
        -DCMAKE_CXX_COMPILER:FILEPATH=${{env.CXX_COMPILER}} \
        -G "Unix Makefiles" \

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} --target all -j 4 --

    - name: Test
      run: |
        cd build
        ctest -C ${{env.BUILD_TYPE}}
